version: "3"
services:
  backend:
      container_name: simple-backend
      image: be:latest
      # build:
      #   context: ./
      #   dockerfile: Dockerfile
      volumes:
        - "./markdown-blog:/var/www/html/"
      ports:
        - 5000:80
